version: "3.9"
   
services:

  redis:
    image: redis
    restart: always

        
  job_scraping:
    restart: always
    build: .
    volumes:
     - .:/code/  
    command: bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"

    
  celery:
    build:
      context: .
    command: 'celery -A job_scraping worker -l info'
    restart: always
    volumes:
     - .:/code/  


  celery-beat:
    build:
      context: .
    command: 'celery -A job_scraping beat -l info'
    restart: always
    volumes:
     - .:/code/ 
